export const pagePath: Readonly<Record<PageName, string>> = {
  home: "home",
  main: "main",
  write: "write",
  modify: "modify",
  diary: "diary",
  onBoarding: "on-borading",
  notFound: "404",
  setting: "setting",
  profile: "setting/profile",
  notice: "setting/notice",
  splash: "",
  signUp: "sign-up",
  recovery: "recovery",
};
